pipeline {
    agent any

    stages {
        stage("Clone Code") {
            steps {
                git url: "https://github.com/mihir280/Todo_APP.git", branch: "master"
                echo "Code Cloned Successfully"
            }
        }

        stage("Build Docker Image") {
            steps {
                sh 'docker build -t mihir064/node-app:latest .'
                echo "Docker Image Built Successfully"
            }
        }

        stage("Push to Docker Hub") {
            steps {
                withCredentials([usernamePassword(credentialsId: "DockerHubCreds", passwordVariable: "dockerPass", usernameVariable: "dockerUser")]) {
                    sh "docker login -u ${dockerUser} -p ${dockerPass}"
                    sh "docker tag mihir064/node-app:latest ${dockerUser}/node-app:latest"
                    sh "docker push ${dockerUser}/node-app:latest"
                }
            }
        }

        stage("Deploy with Docker Compose") {
            steps {
                sh "docker-compose down && docker-compose up -d"
                echo "App Deployed Successfully"
            }
        }
    }
}
